authors:
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  Roye:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  XingMengYue:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
